//PS D:\WorkSpace\Go\Arc> goctl rpc protoc subdomain/resources/proto/subdomain.proto --go_out=subdomain/work --go-grpc_out=subdomain/work --zrpc_out=subdomain/

// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: subdomain/resources/proto/subdomain.proto

// proto 包名

package subdomains

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurPage  int64 `protobuf:"varint,1,opt,name=CurPage,proto3" json:"CurPage,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_subdomain_resources_proto_subdomain_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetCurPage() int64 {
	if x != nil {
		return x.CurPage
	}
	return 0
}

func (x *Page) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 定义入参
type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId  int64  `protobuf:"varint,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	Code    string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	DelFlag string `protobuf:"bytes,4,opt,name=DelFlag,proto3" json:"DelFlag,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_subdomain_resources_proto_subdomain_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDelFlag() string {
	if x != nil {
		return x.DelFlag
	}
	return ""
}

type OptRoleAO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*Role `protobuf:"bytes,1,rep,name=Roles,proto3" json:"Roles,omitempty"`
}

func (x *OptRoleAO) Reset() {
	*x = OptRoleAO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptRoleAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptRoleAO) ProtoMessage() {}

func (x *OptRoleAO) ProtoReflect() protoreflect.Message {
	mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptRoleAO.ProtoReflect.Descriptor instead.
func (*OptRoleAO) Descriptor() ([]byte, []int) {
	return file_subdomain_resources_proto_subdomain_proto_rawDescGZIP(), []int{2}
}

func (x *OptRoleAO) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 定义响应返回
type OptRoleVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptNum int64 `protobuf:"varint,1,opt,name=OptNum,proto3" json:"OptNum,omitempty"`
}

func (x *OptRoleVO) Reset() {
	*x = OptRoleVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptRoleVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptRoleVO) ProtoMessage() {}

func (x *OptRoleVO) ProtoReflect() protoreflect.Message {
	mi := &file_subdomain_resources_proto_subdomain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptRoleVO.ProtoReflect.Descriptor instead.
func (*OptRoleVO) Descriptor() ([]byte, []int) {
	return file_subdomain_resources_proto_subdomain_proto_rawDescGZIP(), []int{3}
}

func (x *OptRoleVO) GetOptNum() int64 {
	if x != nil {
		return x.OptNum
	}
	return 0
}

var File_subdomain_resources_proto_subdomain_proto protoreflect.FileDescriptor

var file_subdomain_resources_proto_subdomain_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x75, 0x62,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x75,
	0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x75, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x60, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x46,
	0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x6c, 0x46, 0x6c,
	0x61, 0x67, 0x22, 0x33, 0x0a, 0x09, 0x4f, 0x70, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x4f, 0x12,
	0x26, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x09, 0x4f, 0x70, 0x74, 0x52, 0x6f,
	0x6c, 0x65, 0x56, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x70, 0x74, 0x4e, 0x75, 0x6d, 0x32, 0x49, 0x0a, 0x0a,
	0x53, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x75, 0x62, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x4f,
	0x1a, 0x15, 0x2e, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x4f, 0x70,
	0x74, 0x52, 0x6f, 0x6c, 0x65, 0x56, 0x4f, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x75, 0x62, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_subdomain_resources_proto_subdomain_proto_rawDescOnce sync.Once
	file_subdomain_resources_proto_subdomain_proto_rawDescData = file_subdomain_resources_proto_subdomain_proto_rawDesc
)

func file_subdomain_resources_proto_subdomain_proto_rawDescGZIP() []byte {
	file_subdomain_resources_proto_subdomain_proto_rawDescOnce.Do(func() {
		file_subdomain_resources_proto_subdomain_proto_rawDescData = protoimpl.X.CompressGZIP(file_subdomain_resources_proto_subdomain_proto_rawDescData)
	})
	return file_subdomain_resources_proto_subdomain_proto_rawDescData
}

var file_subdomain_resources_proto_subdomain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_subdomain_resources_proto_subdomain_proto_goTypes = []interface{}{
	(*Page)(nil),      // 0: subdomains.Page
	(*Role)(nil),      // 1: subdomains.Role
	(*OptRoleAO)(nil), // 2: subdomains.OptRoleAO
	(*OptRoleVO)(nil), // 3: subdomains.OptRoleVO
}
var file_subdomain_resources_proto_subdomain_proto_depIdxs = []int32{
	1, // 0: subdomains.OptRoleAO.Roles:type_name -> subdomains.Role
	2, // 1: subdomains.Subdomains.OperateRole:input_type -> subdomains.OptRoleAO
	3, // 2: subdomains.Subdomains.OperateRole:output_type -> subdomains.OptRoleVO
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_subdomain_resources_proto_subdomain_proto_init() }
func file_subdomain_resources_proto_subdomain_proto_init() {
	if File_subdomain_resources_proto_subdomain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_subdomain_resources_proto_subdomain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_subdomain_resources_proto_subdomain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_subdomain_resources_proto_subdomain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptRoleAO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_subdomain_resources_proto_subdomain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptRoleVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_subdomain_resources_proto_subdomain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subdomain_resources_proto_subdomain_proto_goTypes,
		DependencyIndexes: file_subdomain_resources_proto_subdomain_proto_depIdxs,
		MessageInfos:      file_subdomain_resources_proto_subdomain_proto_msgTypes,
	}.Build()
	File_subdomain_resources_proto_subdomain_proto = out.File
	file_subdomain_resources_proto_subdomain_proto_rawDesc = nil
	file_subdomain_resources_proto_subdomain_proto_goTypes = nil
	file_subdomain_resources_proto_subdomain_proto_depIdxs = nil
}
