// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: subdomain/resources/proto/subdomain.proto

package subdomains

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubdomainsClient is the client API for Subdomains service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubdomainsClient interface {
	OperateRole(ctx context.Context, in *OptRoleAO, opts ...grpc.CallOption) (*OptRoleVO, error)
}

type subdomainsClient struct {
	cc grpc.ClientConnInterface
}

func NewSubdomainsClient(cc grpc.ClientConnInterface) SubdomainsClient {
	return &subdomainsClient{cc}
}

func (c *subdomainsClient) OperateRole(ctx context.Context, in *OptRoleAO, opts ...grpc.CallOption) (*OptRoleVO, error) {
	out := new(OptRoleVO)
	err := c.cc.Invoke(ctx, "/subdomains.Subdomains/OperateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubdomainsServer is the server API for Subdomains service.
// All implementations must embed UnimplementedSubdomainsServer
// for forward compatibility
type SubdomainsServer interface {
	OperateRole(context.Context, *OptRoleAO) (*OptRoleVO, error)
	mustEmbedUnimplementedSubdomainsServer()
}

// UnimplementedSubdomainsServer must be embedded to have forward compatible implementations.
type UnimplementedSubdomainsServer struct {
}

func (UnimplementedSubdomainsServer) OperateRole(context.Context, *OptRoleAO) (*OptRoleVO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperateRole not implemented")
}
func (UnimplementedSubdomainsServer) mustEmbedUnimplementedSubdomainsServer() {}

// UnsafeSubdomainsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubdomainsServer will
// result in compilation errors.
type UnsafeSubdomainsServer interface {
	mustEmbedUnimplementedSubdomainsServer()
}

func RegisterSubdomainsServer(s grpc.ServiceRegistrar, srv SubdomainsServer) {
	s.RegisterService(&Subdomains_ServiceDesc, srv)
}

func _Subdomains_OperateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptRoleAO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubdomainsServer).OperateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subdomains.Subdomains/OperateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubdomainsServer).OperateRole(ctx, req.(*OptRoleAO))
	}
	return interceptor(ctx, in, info, handler)
}

// Subdomains_ServiceDesc is the grpc.ServiceDesc for Subdomains service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subdomains_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subdomains.Subdomains",
	HandlerType: (*SubdomainsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OperateRole",
			Handler:    _Subdomains_OperateRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subdomain/resources/proto/subdomain.proto",
}
