//PS D:\WorkSpace\Go\Arc> goctl rpc protoc db/resources/proto/db.proto --go_out=db/work --go-grpc_out=db/work --zrpc_out=db/

// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: db/resources/proto/db.proto

// proto 包名

package dbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CenterDataApi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AfterSql      string `protobuf:"bytes,1,opt,name=AfterSql,proto3" json:"AfterSql,omitempty"`
	SqlParam      string `protobuf:"bytes,2,opt,name=SqlParam,proto3" json:"SqlParam,omitempty"`
	ApiId         int64  `protobuf:"varint,3,opt,name=ApiId,proto3" json:"ApiId,omitempty"`
	CenterName    string `protobuf:"bytes,4,opt,name=CenterName,proto3" json:"CenterName,omitempty"`
	ApiName       string `protobuf:"bytes,5,opt,name=ApiName,proto3" json:"ApiName,omitempty"`
	ApiPath       string `protobuf:"bytes,6,opt,name=ApiPath,proto3" json:"ApiPath,omitempty"`
	OpType        string `protobuf:"bytes,7,opt,name=OpType,proto3" json:"OpType,omitempty"`
	CallSource    string `protobuf:"bytes,8,opt,name=CallSource,proto3" json:"CallSource,omitempty"`
	ApiParam      string `protobuf:"bytes,9,opt,name=ApiParam,proto3" json:"ApiParam,omitempty"`
	BeforeSql     string `protobuf:"bytes,10,opt,name=BeforeSql,proto3" json:"BeforeSql,omitempty"`
	DecryptFlag   string `protobuf:"bytes,11,opt,name=DecryptFlag,proto3" json:"DecryptFlag,omitempty"`
	DecryptFld    string `protobuf:"bytes,12,opt,name=DecryptFld,proto3" json:"DecryptFld,omitempty"`
	BeforeExtend  string `protobuf:"bytes,13,opt,name=BeforeExtend,proto3" json:"BeforeExtend,omitempty"`
	BeforeExtend2 string `protobuf:"bytes,14,opt,name=BeforeExtend2,proto3" json:"BeforeExtend2,omitempty"`
}

func (x *CenterDataApi) Reset() {
	*x = CenterDataApi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_resources_proto_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CenterDataApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterDataApi) ProtoMessage() {}

func (x *CenterDataApi) ProtoReflect() protoreflect.Message {
	mi := &file_db_resources_proto_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterDataApi.ProtoReflect.Descriptor instead.
func (*CenterDataApi) Descriptor() ([]byte, []int) {
	return file_db_resources_proto_db_proto_rawDescGZIP(), []int{0}
}

func (x *CenterDataApi) GetAfterSql() string {
	if x != nil {
		return x.AfterSql
	}
	return ""
}

func (x *CenterDataApi) GetSqlParam() string {
	if x != nil {
		return x.SqlParam
	}
	return ""
}

func (x *CenterDataApi) GetApiId() int64 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *CenterDataApi) GetCenterName() string {
	if x != nil {
		return x.CenterName
	}
	return ""
}

func (x *CenterDataApi) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *CenterDataApi) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *CenterDataApi) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *CenterDataApi) GetCallSource() string {
	if x != nil {
		return x.CallSource
	}
	return ""
}

func (x *CenterDataApi) GetApiParam() string {
	if x != nil {
		return x.ApiParam
	}
	return ""
}

func (x *CenterDataApi) GetBeforeSql() string {
	if x != nil {
		return x.BeforeSql
	}
	return ""
}

func (x *CenterDataApi) GetDecryptFlag() string {
	if x != nil {
		return x.DecryptFlag
	}
	return ""
}

func (x *CenterDataApi) GetDecryptFld() string {
	if x != nil {
		return x.DecryptFld
	}
	return ""
}

func (x *CenterDataApi) GetBeforeExtend() string {
	if x != nil {
		return x.BeforeExtend
	}
	return ""
}

func (x *CenterDataApi) GetBeforeExtend2() string {
	if x != nil {
		return x.BeforeExtend2
	}
	return ""
}

type CenterDataApiVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiSlice []*CenterDataApi `protobuf:"bytes,1,rep,name=ApiSlice,proto3" json:"ApiSlice,omitempty"`
}

func (x *CenterDataApiVO) Reset() {
	*x = CenterDataApiVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_resources_proto_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CenterDataApiVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterDataApiVO) ProtoMessage() {}

func (x *CenterDataApiVO) ProtoReflect() protoreflect.Message {
	mi := &file_db_resources_proto_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterDataApiVO.ProtoReflect.Descriptor instead.
func (*CenterDataApiVO) Descriptor() ([]byte, []int) {
	return file_db_resources_proto_db_proto_rawDescGZIP(), []int{1}
}

func (x *CenterDataApiVO) GetApiSlice() []*CenterDataApi {
	if x != nil {
		return x.ApiSlice
	}
	return nil
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurPage  int64 `protobuf:"varint,2,opt,name=CurPage,proto3" json:"CurPage,omitempty"`
	PageSize int64 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_resources_proto_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_db_resources_proto_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_db_resources_proto_db_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetCurPage() int64 {
	if x != nil {
		return x.CurPage
	}
	return 0
}

func (x *Page) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DataContentDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterDataApi *CenterDataApi `protobuf:"bytes,1,opt,name=CenterDataApi,proto3" json:"CenterDataApi,omitempty"`
	Page          *Page          `protobuf:"bytes,2,opt,name=Page,proto3" json:"Page,omitempty"`
}

func (x *DataContentDTO) Reset() {
	*x = DataContentDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_resources_proto_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataContentDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataContentDTO) ProtoMessage() {}

func (x *DataContentDTO) ProtoReflect() protoreflect.Message {
	mi := &file_db_resources_proto_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataContentDTO.ProtoReflect.Descriptor instead.
func (*DataContentDTO) Descriptor() ([]byte, []int) {
	return file_db_resources_proto_db_proto_rawDescGZIP(), []int{3}
}

func (x *DataContentDTO) GetCenterDataApi() *CenterDataApi {
	if x != nil {
		return x.CenterDataApi
	}
	return nil
}

func (x *DataContentDTO) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type DataMapVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maps  []*AnyMap `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty"`
	Total int64     `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *DataMapVO) Reset() {
	*x = DataMapVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_resources_proto_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMapVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMapVO) ProtoMessage() {}

func (x *DataMapVO) ProtoReflect() protoreflect.Message {
	mi := &file_db_resources_proto_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMapVO.ProtoReflect.Descriptor instead.
func (*DataMapVO) Descriptor() ([]byte, []int) {
	return file_db_resources_proto_db_proto_rawDescGZIP(), []int{4}
}

func (x *DataMapVO) GetMaps() []*AnyMap {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *DataMapVO) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AnyMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]*anypb.Any `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AnyMap) Reset() {
	*x = AnyMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_resources_proto_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnyMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyMap) ProtoMessage() {}

func (x *AnyMap) ProtoReflect() protoreflect.Message {
	mi := &file_db_resources_proto_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyMap.ProtoReflect.Descriptor instead.
func (*AnyMap) Descriptor() ([]byte, []int) {
	return file_db_resources_proto_db_proto_rawDescGZIP(), []int{5}
}

func (x *AnyMap) GetData() map[string]*anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_db_resources_proto_db_proto protoreflect.FileDescriptor

var file_db_resources_proto_db_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64,
	0x62, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x03,
	0x0a, 0x0d, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x69, 0x12,
	0x1a, 0x0a, 0x08, 0x41, 0x66, 0x74, 0x65, 0x72, 0x53, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x41, 0x66, 0x74, 0x65, 0x72, 0x53, 0x71, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x71, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53,
	0x71, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x41, 0x70, 0x69, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x69, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x69, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x6c,
	0x6c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43,
	0x61, 0x6c, 0x6c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x70, 0x69,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x70, 0x69,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x53,
	0x71, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65,
	0x53, 0x71, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x46, 0x6c,
	0x61, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x46, 0x6c, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x46, 0x6c, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x42, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x42, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x32, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x32, 0x22,
	0x41, 0x0a, 0x0f, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x69,
	0x56, 0x4f, 0x12, 0x2e, 0x0a, 0x08, 0x41, 0x70, 0x69, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x62, 0x73, 0x2e, 0x43, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x69, 0x52, 0x08, 0x41, 0x70, 0x69, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x22, 0x3c, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x75,
	0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x75, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x69, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44,
	0x54, 0x4f, 0x12, 0x38, 0x0a, 0x0d, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x41, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x62, 0x73, 0x2e,
	0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x69, 0x52, 0x0d, 0x43,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x69, 0x12, 0x1d, 0x0a, 0x04,
	0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x62, 0x73,
	0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x22, 0x42, 0x0a, 0x09, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x61, 0x70, 0x56, 0x4f, 0x12, 0x1f, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x62, 0x73, 0x2e, 0x41, 0x6e, 0x79,
	0x4d, 0x61, 0x70, 0x52, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x82, 0x01, 0x0a, 0x06, 0x41, 0x6e, 0x79, 0x4d, 0x61, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x62, 0x73, 0x2e, 0x41,
	0x6e, 0x79, 0x4d, 0x61, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x4d, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x32, 0x7c, 0x0a, 0x03, 0x44, 0x62, 0x73, 0x12, 0x3e, 0x0a, 0x12, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70,
	0x69, 0x12, 0x12, 0x2e, 0x64, 0x62, 0x73, 0x2e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x41, 0x70, 0x69, 0x1a, 0x14, 0x2e, 0x64, 0x62, 0x73, 0x2e, 0x43, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x70, 0x69, 0x56, 0x4f, 0x12, 0x35, 0x0a, 0x0e, 0x72,
	0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x12, 0x13, 0x2e,
	0x64, 0x62, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44,
	0x54, 0x4f, 0x1a, 0x0e, 0x2e, 0x64, 0x62, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70,
	0x56, 0x4f, 0x42, 0x06, 0x5a, 0x04, 0x64, 0x62, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_db_resources_proto_db_proto_rawDescOnce sync.Once
	file_db_resources_proto_db_proto_rawDescData = file_db_resources_proto_db_proto_rawDesc
)

func file_db_resources_proto_db_proto_rawDescGZIP() []byte {
	file_db_resources_proto_db_proto_rawDescOnce.Do(func() {
		file_db_resources_proto_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_resources_proto_db_proto_rawDescData)
	})
	return file_db_resources_proto_db_proto_rawDescData
}

var file_db_resources_proto_db_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_db_resources_proto_db_proto_goTypes = []interface{}{
	(*CenterDataApi)(nil),   // 0: dbs.CenterDataApi
	(*CenterDataApiVO)(nil), // 1: dbs.CenterDataApiVO
	(*Page)(nil),            // 2: dbs.Page
	(*DataContentDTO)(nil),  // 3: dbs.DataContentDTO
	(*DataMapVO)(nil),       // 4: dbs.DataMapVO
	(*AnyMap)(nil),          // 5: dbs.AnyMap
	nil,                     // 6: dbs.AnyMap.DataEntry
	(*anypb.Any)(nil),       // 7: google.protobuf.Any
}
var file_db_resources_proto_db_proto_depIdxs = []int32{
	0, // 0: dbs.CenterDataApiVO.ApiSlice:type_name -> dbs.CenterDataApi
	0, // 1: dbs.DataContentDTO.CenterDataApi:type_name -> dbs.CenterDataApi
	2, // 2: dbs.DataContentDTO.Page:type_name -> dbs.Page
	5, // 3: dbs.DataMapVO.maps:type_name -> dbs.AnyMap
	6, // 4: dbs.AnyMap.data:type_name -> dbs.AnyMap.DataEntry
	7, // 5: dbs.AnyMap.DataEntry.value:type_name -> google.protobuf.Any
	0, // 6: dbs.Dbs.queryCenterDataApi:input_type -> dbs.CenterDataApi
	3, // 7: dbs.Dbs.rpcServiceExec:input_type -> dbs.DataContentDTO
	1, // 8: dbs.Dbs.queryCenterDataApi:output_type -> dbs.CenterDataApiVO
	4, // 9: dbs.Dbs.rpcServiceExec:output_type -> dbs.DataMapVO
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_db_resources_proto_db_proto_init() }
func file_db_resources_proto_db_proto_init() {
	if File_db_resources_proto_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_resources_proto_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CenterDataApi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_resources_proto_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CenterDataApiVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_resources_proto_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_resources_proto_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataContentDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_resources_proto_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMapVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_resources_proto_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnyMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_resources_proto_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_resources_proto_db_proto_goTypes,
		DependencyIndexes: file_db_resources_proto_db_proto_depIdxs,
		MessageInfos:      file_db_resources_proto_db_proto_msgTypes,
	}.Build()
	File_db_resources_proto_db_proto = out.File
	file_db_resources_proto_db_proto_rawDesc = nil
	file_db_resources_proto_db_proto_goTypes = nil
	file_db_resources_proto_db_proto_depIdxs = nil
}
