// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: subdomain.proto

package subdomainsclient

import (
	"context"

	"Arc/subdomain/work/subdomains"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OptRoleAO = subdomains.OptRoleAO
	OptRoleVO = subdomains.OptRoleVO
	Page      = subdomains.Page
	Role      = subdomains.Role

	Subdomains interface {
		OperateRole(ctx context.Context, in *OptRoleAO, opts ...grpc.CallOption) (*OptRoleVO, error)
	}

	defaultSubdomains struct {
		cli zrpc.Client
	}
)

func NewSubdomains(cli zrpc.Client) Subdomains {
	return &defaultSubdomains{
		cli: cli,
	}
}

func (m *defaultSubdomains) OperateRole(ctx context.Context, in *OptRoleAO, opts ...grpc.CallOption) (*OptRoleVO, error) {
	client := subdomains.NewSubdomainsClient(m.cli.Conn())
	return client.OperateRole(ctx, in, opts...)
}
