// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"Arc/front/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/queryCenterDataApi",
				Handler: queryCenterDataApiHandler(serverCtx),
			},
		},
		rest.WithPrefix("/front"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/queryRole",
				Handler: queryRoleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/front/role"),
	)
}
