// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: db.proto

package server

import (
	"context"

	"Arc/db/internal/logic"
	"Arc/db/internal/svc"
	"Arc/db/work/dbs"
)

type DbsServer struct {
	svcCtx *svc.ServiceContext
	dbs.UnimplementedDbsServer
}

func NewDbsServer(svcCtx *svc.ServiceContext) *DbsServer {
	return &DbsServer{
		svcCtx: svcCtx,
	}
}

func (s *DbsServer) QueryCenterDataApi(ctx context.Context, in *dbs.CenterDataApi) (*dbs.CenterDataApiVO, error) {
	l := logic.NewQueryCenterDataApiLogic(ctx, s.svcCtx)
	return l.QueryCenterDataApi(in)
}

func (s *DbsServer) RpcServiceExec(ctx context.Context, in *dbs.DataContentDTO) (*dbs.DataMapVO, error) {
	l := logic.NewRpcServiceExecLogic(ctx, s.svcCtx)
	return l.RpcServiceExec(in)
}
