// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: subdomain.proto

package server

import (
	"context"

	"Arc/subdomain/internal/logic"
	"Arc/subdomain/internal/svc"
	"Arc/subdomain/work/subdomains"
)

type SubdomainsServer struct {
	svcCtx *svc.ServiceContext
	subdomains.UnimplementedSubdomainsServer
}

func NewSubdomainsServer(svcCtx *svc.ServiceContext) *SubdomainsServer {
	return &SubdomainsServer{
		svcCtx: svcCtx,
	}
}

func (s *SubdomainsServer) OperateRole(ctx context.Context, in *subdomains.OptRoleAO) (*subdomains.OptRoleVO, error) {
	l := logic.NewOperateRoleLogic(ctx, s.svcCtx)
	return l.OperateRole(in)
}
